### PR TITLE
fix: Ensure issues from other repositories are handled

### LINKED ISSUE #1: Only closes issues in repository the PR was created in
### Steps to Reproduce

1. Mention another repository in the "fixes ..." comment
2. Close the PR

### Expected Result

The "PR was released" comment should be posted in the repository which is mentioned in the "fixes ..." link.

### Actual Result

It creates a comment in the repository the issue was created in: https://github.com/getsentry/sentry-javascript/pull/15971#issuecomment-2787106659

### PR DESCRIPTION
**Pull request by mydea**
Closes https://github.com/getsentry/release-comment-issues-gh-action/issues/1

### CODE REVIEW

File: dist/index.js [hunk 1]
```diff
@@ -23769,31 +23769,33 @@ async function run() {
...
       const body = `${RELEASE_COMMENT_HEADING}
 
-This issue was referenced by PR #${pr.prNumber}, which was included in the [${version2} release](https://github.com/${owner}/${repo}/releases/tag/${version2}).`;
+This issue was referenced by PR ${prLink}, which was included in the [${version2} release](https://github.com/${owner}/${repo}/releases/tag/${version2}).`;
       core.debug(`Creating comment for issue #${issue.number}`);
       try {
         await octokit.rest.issues.createComment({
-          repo,
+          repo: issueRepo,
           owner,
```
Comment (lforst) [inline dist/index.js:23793]: owner is also important I think!

Comment (mydea) [reply dist/index.js:23793]: added a comment here, we enforce the same owner here as the release!

**Review by lforst — APPROVED** [review]
